image: 
  repository: omarkamal1/my-reload-counter-py-app
  version: v1.0.0

namespace:
  Name: default

ports:
  redis_port: 6379
  app_port: 8000

app_template:
  name: myPythonapp  

redis_template:
  name: myPythonapp    

# The number of application's pods that will  be created  
replication_count: 1 

metadata: 
  labels:
    env: dev
    date: "25-07-2022"